from resources.emoji import EMOJI_LIST

"""Category metadata pulled from the legacy JavaScript source."""

CATEGORY_LIST = [
    {
        "name": "P0",
        "description": "Standard (P0)",
        "picture": "https://i.imgur.com/nzndLpV.png",
        "emoji": EMOJI_LIST["_P0"],
        "color": "#B6B3AA",
    },
    {
        "name": "P1",
        "description": "Protected (P1)",
        "picture": "https://i.imgur.com/ndBCphI.png",
        "emoji": EMOJI_LIST["_P1"],
        "color": "#FEC861",
    },
    {
        "name": "P2",
        "description": "Prime (P2)",
        "picture": "https://i.imgur.com/ndBCphI.png",
        "emoji": EMOJI_LIST["_P2"],
        "color": "#FFD481",
    },
    {
        "name": "P3",
        "description": "Bootcamp (P3)",
        "picture": "https://i.imgur.com/bIfMjbQ.png",
        "thread": "https://atelier801.com/topic?f=6&t=48030",
        "emoji": EMOJI_LIST["_P3"],
        "submissionlimit": 3,
        "submissionRules": [
            "Map should be able to be easily done in 2 minutes.",
            "Do not use anchors.",
            "Map should stay onscreen as much as possible.",
            "Map should not be easily breakable if using dynamic grounds.",
            "Map should be straightforward. If you look at the map, play it for a few minutes and still have no idea how to do it, then regular players will take 10 times that amount of time to figure it out as well.",
            "Map should not spam the same obstacles over and over.",
            "Map should be as original as possible but if a map's only/main negative point is that some parts of the map exist in other maps but the map itself is not a copy or close to being one, then unoriginality should be ignored.",
            "Map should not be exceedingly hard, nor easy (a few on either end of that spectrum are welcome, but not a lot).",
            "Map should not be luck based.",
            "Map should not have lava/ice/tramp spam.",
        ],
        "decisions": ["left_as_is", "will_be_discussed", "ignored"],
        "color": "#717B3C",
    },
    {
        "name": "P4",
        "description": "Shaman (P4)",
        "picture": "https://i.imgur.com/43fUNoX.png",
        "thread": "https://atelier801.com/topic?f=6&t=48016",
        "emoji": EMOJI_LIST["_P4"],
        "submissionlimit": 4,
        "submissionRules": [
            "No 1 or 2 plank/generic solutions.",
            "Maps which challenge shamans to try interesting and new builds.",
            "Consideration for hard mode is encouraged but not necessary.",
            "Maps shouldn't be too hard for newer shamans.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#95D9D6",
    },
    {
        "name": "P5",
        "description": "Art (P5)",
        "picture": "https://i.imgur.com/DWqAcW0.png",
        "thread": "https://atelier801.com/topic?f=6&t=48019",
        "emoji": EMOJI_LIST["_P5"],
        "submissionlimit": 4,
        "submissionRules": [
            "There must be some gameplay to the map. Unless the art is of the highest quality, simply wjing/building over the art will not be acceptable.",
            "Art must be well aligned/should look great.",
            "Art should be kept as lag-free as possible.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#C24A1F",
    },
    {
        "name": "P6",
        "description": "Mechanism (P6)",
        "picture": "https://i.imgur.com/deE6DIX.png",
        "thread": "https://atelier801.com/topic?f=6&t=48020",
        "emoji": EMOJI_LIST["_P6"],
        "submissionlimit": 4,
        "submissionRules": [
            "Will include a variety of maps that cover all categories listed.",
            "Maps should have good gameplay. Maps containing awesome glitches but lack gameplay will not be accepted.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#D8D8D9",
    },
    {
        "name": "P7",
        "description": "No Shaman (P7)",
        "picture": "https://i.imgur.com/kb1U7IH.png",
        "thread": "https://atelier801.com/topic?f=6&t=48021",
        "emoji": EMOJI_LIST["_P7"],
        "submissionlimit": 4,
        "submissionRules": [
            "Map should be generally completable by mice of various skill but reward better skilled mice.",
            "Walljumping should be kept to a minimum.",
            "Can include soulmate, collision and mechanism.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#332C26",
    },
    {
        "name": "P8",
        "description": "Double Shaman (P8)",
        "picture": "https://i.imgur.com/dMCj6ZN.png",
        "thread": "https://atelier801.com/topic?f=6&t=48022",
        "emoji": EMOJI_LIST["_P8"],
        "submissionlimit": 4,
        "submissionRules": [
            "Maps can generally be more difficult/complex to allow two shams to cooperate.",
            "There must not be a situation where the death of one sham makes the map unfinishable for mice.",
            "Maps must not encourage the shamans to fight.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#FBA5F0",
    },
    {
        "name": "P9",
        "description": "Miscellaneous (P9)",
        "picture": "https://i.imgur.com/y4FcHyi.png",
        "thread": "https://atelier801.com/topic?f=6&t=48023",
        "emoji": EMOJI_LIST["_P9"],
        "submissionlimit": 4,
        "submissionRules": [
            "Soulmate/Collision maps can go here",
            "Maps which do not fit under exactly one category.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#FFD480",
    },
    {
        "name": "P10",
        "description": "Survivor (P10)",
        "picture": "https://i.imgur.com/GSzC6qh.png",
        "thread": "https://atelier801.com/topic?f=6&t=98668",
        "emoji": EMOJI_LIST["_P10"],
        "submissionlimit": 2,
        "submissionRules": [
            "Survivor maps are special maps for a game type called Survivor.",
            "In this game the shaman must kill the mice. The remaining mice will be rewarded with one cheese.",
            "You must not add holes to your map.",
            "You can add cheese, but avoid spamming them around.",
            "The shaman must have enough space to move around and to kill the mice.",
            "Mice must have enough space to flee as fast as possible.",
            "Backgrounds and decorations of any kind are not permitted. The only exceptions are for those in themed rotations.",
        ],
        "decisions": ["left_as_is", "will_be_discussed", "ignored"],
        "color": "#353434",
    },
    {
        "name": "P11",
        "description": "Vampire Surv (P11)",
        "picture": "https://i.imgur.com/m6atPga.png",
        "thread": "https://atelier801.com/topic?f=6&t=98669",
        "emoji": EMOJI_LIST["_P11"],
        "submissionlimit": 2,
        "submissionRules": [
            "Vampire maps are special maps for the Survivor game.",
            "In this game there is no shaman: mice are infected and become vampires. The objective is to avoid being infected. Surviving mice will be rewarded with one cheese.",
            "You must not add any cages.",
            "You must not add deep water or trampolines.",
            "You must not spam the map with cheese.",
            "The map must have enough space for mice to run from the vampires.",
        ],
        "decisions": ["left_as_is", "will_be_discussed", "ignored"],
        "color": "#544931",
    },
    {
        "name": "P12",
        "description": "Mechanism no Shaman (P12)",
        "picture": "https://i.imgur.com/euUbAfn.png",
        "emoji": EMOJI_LIST["_P12"],
        "color": "#D8D8D9",
    },
    {
        "name": "P13",
        "description": "Lower bootcamp (P13)",
        "picture": "https://i.imgur.com/Q8Mf3AX.png",
        "emoji": EMOJI_LIST["_P13"],
        "color": "#8E9565",
    },
    {
        "name": "P17",
        "description": "Racing (P17)",
        "picture": "https://i.imgur.com/sgNPHFA.png",
        "thread": "https://atelier801.com/topic?f=6&t=212241",
        "emoji": EMOJI_LIST["_P17"],
        "submissionlimit": 2,
        "submissionRules": [
            "No shaman objects including anchors",
            "No backgrounds",
            "No decorations (flowers, plants, etc)",
            "No collision/soulmate/night/scrolling/defilante maps",
            "No dynamic grounds",
            "Use default properties for grounds, with exceptions for wj tramps and such.",
            "Use common sense",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#C32C12",
    },
    {
        "name": "P18",
        "description": "Defilante (P18)",
        "picture": "https://i.imgur.com/H0FpaWH.png",
        "thread": "https://atelier801.com/topic?f=6&t=218925",
        "emoji": EMOJI_LIST["_P18"],
        "submissionlimit": 5,
        "submissionRules": [
            "Each map needs at least two paths of varying difficulty.",
            "Taking the harder path should be more rewarding.",
            "Keep walljumping to a minimum.",
            "Maps need to move, they cannot be static.",
            "Maps shouldn't move too slow or too fast.",
            "Maps need to have freescroll as to not punish people who go too fast.",
            "No soulmate, collision, or nightmode",
        ],
        "decisions": ["left_as_is", "will_be_discussed", "ignored"],
        "color": "#7DCA24",
    },
    {
        "name": "P19",
        "description": "Music (P19)",
        "picture": "https://i.imgur.com/dWkfUyX.png",
        "emoji": EMOJI_LIST["_P19"],
        "color": "#9CABB5",
    },
    {
        "name": "P20",
        "description": "Normal Survivor Test (P20)",
        "picture": "https://i.imgur.com/1dyJuy5.png",
        "emoji": EMOJI_LIST["_P20"],
        "color": "#353434",
    },
    {
        "name": "P21",
        "description": "Vampire Survivor Test (P21)",
        "picture": "https://i.imgur.com/v4UqRSb.png",
        "emoji": EMOJI_LIST["_P21"],
        "color": "#544931",
    },
    {
        "name": "P22",
        "description": "Tribe house (P22)",
        "picture": "https://i.imgur.com/X2bHHoq.png",
        "emoji": EMOJI_LIST["_P22"],
        "color": "#7E5F40",
    },
    {
        "name": "P23",
        "description": "Bootcamp Test (P23)",
        "picture": "https://i.imgur.com/UmSCzcs.png",
        "emoji": EMOJI_LIST["_P23"],
        "color": "#717B3C",
    },
    {
        "name": "P24",
        "description": "Dual Surv (P24)",
        "picture": "https://i.imgur.com/PWDFBDW.png",
        "emoji": EMOJI_LIST["_P24"],
        "submissionlimit": 3,
        "submissionRules": [
            "Dual Shaman Survivor maps are special maps for a game type called Survivor, but maps in this category have two shamans instead of one.",
            "In this game the shamans must kill the mice. The remaining mice will be rewarded with one cheese.",
            "You must not add holes to your map.",
            "You can add cheese, but avoid spamming them around.",
            "The shamans must have enough space to move around and to kill the mice, even if one of the shamans is AFK.",
            "Mice must have enough space to flee as fast as possible, even with two shamans attacking them.",
            "Backgrounds and decorations of any kind are not permitted. The only exceptions are for those in themed rotations.",
        ],
        "decisions": ["left_as_is", "will_be_discussed", "ignored"],
        "color": "#C3C3C3",
    },
    {
        "name": "P27",
        "description": "Retro Racing (P27)",
        "picture": "https://i.imgur.com/vavqwda.png",
        "emoji": EMOJI_LIST["_P27"],
        "color": "#C32C12",
    },
    {
        "name": "P32",
        "description": "Double Shaman Test (P32)",
        "picture": "https://i.imgur.com/nd09QvE.png",
        "emoji": EMOJI_LIST["_P32"],
        "color": "#FBA5F0",
    },
    {
        "name": "P34",
        "description": "Dual Shaman Survivor Test (P34)",
        "picture": "https://i.imgur.com/7Pc6fHb.png",
        "emoji": EMOJI_LIST["_P34"],
        "color": "#C3C3C3",
    },
    {
        "name": "P37",
        "description": "Nitro Racing (P37)",
        "picture": "https://i.imgur.com/zCSaGV3.png",
        "emoji": EMOJI_LIST["_P37"],
        "color": "#C32C12",
    },
    {
        "name": "P38",
        "description": "Racing Archive (P38)",
        "picture": "https://i.imgur.com/HibNSyQ.png",
        "emoji": EMOJI_LIST["_P38"],
        "color": "#C32C12",
    },
    {
        "name": "P41",
        "description": "Minigame (P41)",
        "picture": "https://i.imgur.com/OG0CIW3.png",
        "emoji": EMOJI_LIST["_P41"],
        "color": "#F7BF54",
    },
    {
        "name": "P42",
        "description": "No Shaman Test (P42)",
        "picture": "https://i.imgur.com/hUEXr2K.png",
        "emoji": EMOJI_LIST["_P42"],
        "color": "#95D9D6",
    },
    {
        "name": "P43",
        "description": "Inappropriate (P43)",
        "picture": "https://i.imgur.com/Bu1k0Px.png",
        "emoji": EMOJI_LIST["_P43"],
        "color": "#F50000",
    },
    {
        "name": "P44",
        "description": "Deleted (P44)",
        "picture": "https://i.imgur.com/Bu1k0Px.png",
        "emoji": EMOJI_LIST["_P43"],
        "color": "#F50000",
    },
    {
        "name": "P60",
        "description": "Thematic Test (P60)",
        "picture": "https://i.imgur.com/yJuncPP.png",
        "emoji": EMOJI_LIST["_P66"],
        "color": "#368DCB",
    },
    {
        "name": "P66",
        "description": "Thematic (P66)",
        "picture": "https://i.imgur.com/yJuncPP.png",
        "emoji": EMOJI_LIST["_P66"],
        "submissionlimit": -1,  # No limit
        "submissionRules": [
            "Map should meet all P1 and P5 requirements.",
            "The maps will be depermed and stored as soon as their event/season is over.",
            "The maps will not be discussed, we will straight add them in rotation throughout their event/season.",
        ],
        "decisions": ["left_as_is", "p1ed", "will_be_discussed", "ignored"],
        "color": "#368DCB",
    },
]

# Apply persisted runtime overrides (map limit / criteria) edited from the panel.
try:
    from resources.category_overrides import apply_overrides as _apply_category_overrides

    _apply_category_overrides(CATEGORY_LIST)
except Exception:  # pragma: no cover - overrides are best-effort
    pass
